# Generated by Django 3.1.7 on 2021-04-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_review_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='createAt',
            new_name='createdAt',
        ),
    ]
