# Generated by Django 3.1.7 on 2021-04-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210422_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='createdAt',
            new_name='createAt',
        ),
    ]
